### ISSUE TITLE
Download Button for DT::dataTableOutput

### ISSUE THREAD

**Issue by kmezhoud** [PPgp/wppExplorer#5]
Dear Maintainer,
Shiny app is great  way to make easy access to features developed in wppExplorer.
In some case user need to use the output statistics and download.
I suggest to add a button to download the instance data.table. Like this.

server
```{r}
output$dl_tpop_tab <- shiny::downloadHandler(
  filename = function() { paste0("total_population_tab.csv") },
  content = function(file) {
    get_data(tpop[input$tpop_rows_all,], vars = NULL,
            rows = NULL,
            na.rm = FALSE) %>%
      write.csv(file, row.names = FALSE)
  }
)

output$tpop <- DT::renderDataTable({
  shiny::withProgress(message = 'loading total population ...', value = 1, {

 dt <- get_data( total_pop)
  data.table(dt
  })
``` 
get_data is a function where has access to global data

ui
```{r}
 downloadLink("dl_tpop_tab", "", class = "fa fa-download alignright"),
                           DT::dataTableOutput(outputId = "tpop")
```
 Thanks

**Comment by hanase** [comment]
Thanks for the suggestion @kmezhoud - I'll do that.

**Comment by hanase** [comment]
This has now been added. Online versions have been updated (https://bayespop.shinyapps.io/wpp2019explorer), the CRAN version will follow. Thanks again for the suggestion @kmezhoud.
